[package]
name = "pigeon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.12.0"
winit = "0.26"
chrono = "0.4"
cfg-if = "1.0"
pollster = "0.2.5"
log = "0.4"
fern = "0.6"
pigeon-parrot = {path = "../parrot" }